### ISSUE TITLE
change plot_ly export format from png to svg 

### ISSUE THREAD

**Issue by fengyq** [UMMS-Biocore/debrowser-docs#8]
Hi,

Thank you very much for providing this cool and useful package.

I found the picture for export by default from plot_ly is png, which is of low quality. I could use trace to edit the package or write the plotting code by myself, but it is annoying to change the code repeatedly.

Could you add an SVG format to plot_ly() exporting options?
Like this:
plot_ly() %>% config(toImageButtonOptions = list(format = "svg"))

Thanks.

**Comment by nephantes** [comment]
I added an option to the menu to enable SVG download for plotly plots. To enable, please go to plots options and check Download SVG option under size&margins menu. I added this functionality to all plotly plots in DEBrowser. Let me know how it works for you.

<img width="200" alt="Screenshot 2019-08-09 16 01 22" src="https://user-images.githubusercontent.com/4869692/62806020-9ef6b900-babf-11e9-9c51-5909e90c452e.png">

**Comment by fengyq** [comment]
Thank you so much!
