### ISSUE TITLE
Problems launching the browser

### ISSUE THREAD

**Issue by A-Catarina** [UMMS-Biocore/debrowser-docs#9]
Hi!

Congrats on creating such an helpful tool!
I struggled a little to install it on Ubuntu18.04 but finally managed to do so. However, when I run the startDEBrowser() command instead of launching the web browser the following message pops up: 

Listening on http://127.0.0.1:4994
sh: 1: /usr/bin/open: not found

I have confirmed that all needed dependencies are installed as well as shiny.
Could you guys help me understand what is going on? I would really appreciate it.

Kind regards,

Catarina

**Comment by nephantes** [comment]
Are you trying to run DEBrowser on a remote machine?

**Comment by A-Catarina** [comment]
No

**Comment by nephantes** [comment]
What are the web browsers installed in your linux machine? Could you try installing Chrome, log out/log in and try starting DEBrowser from R again?
When you got the error does it exit or hang? If it hangs there, could you try opening your web browser and go to that url "http://127.0.0.1:4994"  (Make sure the port is right)

**Comment by A-Catarina** [comment]
I have Firefox and chormium installed. I'm not sure if it is possible to install Chrome on linux hence chromium is used as its replacement... 
When I get the error message it hangs permanently until I force its abortion.
Thank you so much!! I will follow your advice and let you know.

**Comment by A-Catarina** [comment]
Problem solved! Turns out I only had to go to the url. It works fine on Firefox.
Thank you and best luck!
